server:
  port: 7080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: passenger-service
          uri: http://ms-passenger:4081
          predicates:
            - Path=/passengers/**
        - id: driver-service
          uri: http://ms-driver:4082
          predicates:
            - Path=/drivers/**
        - id: trip-service
          uri: http://ms-driver:4083
          predicates:
            - Path=/trips/**            
      default-filters:
        - AddResponseHeader=X-Gateway, AYGO-Gateway
